package examples.stylepicker.studio;

import swingtree.UI;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;

/**
 *  Turns a {@link StyleConfig} into the <b>source code of a full
 *  {@link swingtree.style.StyleSheet} subclass</b> — the text the user copies
 *  out of the studio and drops into their own application.
 *
 *  <p>The emitted rules mirror {@link LookSheet#apply} field-for-field, so a
 *  component tagged {@code .group("CARD")} (or simply of a given type) in the
 *  user's app ends up looking exactly like the preview in the studio. Group
 *  names are emitted as plain strings so the snippet is self-contained (swap them
 *  for an {@code enum} in your own code for refactor-safety); types are emitted
 *  as fully-qualified {@code .class} literals.</p>
 */
final class LookCode {

    private static final UI.Corner[] CORNERS = { UI.Corner.TOP_LEFT, UI.Corner.TOP_RIGHT, UI.Corner.BOTTOM_RIGHT, UI.Corner.BOTTOM_LEFT };

    static String generate(StyleConfig cfg) {
        StringBuilder out = new StringBuilder();
        out.append("import swingtree.UI;\n")
           .append("import swingtree.style.StyleSheet;\n")
           .append("import java.awt.Color;\n\n")
           .append("/** Generated by the SwingTree Style Studio. */\n")
           .append("public final class MyLookSheet extends StyleSheet {\n\n")
           .append("    @Override\n")
           .append("    protected void configure() {\n");

        boolean any = false;
        for (StyleTarget t : StyleTarget.all()) {
            List<String> lines = rulesFor(cfg.styleFor(t));
            if (lines.isEmpty()) continue;
            any = true;
            String selector = t.isGroup()
                ? "group(\"" + t.group().name() + "\")"
                : "type(" + t.type().getName() + ".class)";
            out.append("        add(").append(selector).append(", it -> it\n");
            for (String line : lines)
                out.append("            ").append(line).append('\n');
            out.append("        );\n");
        }
        if (!any)
            out.append("        // (nothing configured yet — tweak some targets and Apply)\n");

        out.append("    }\n")
           .append("}\n");
        return out.toString();
    }

    /** The list of ".xyz(...)" calls for one target, or empty if it overrides nothing. */
    private static List<String> rulesFor(GroupStyle s) {
        List<String> l = new ArrayList<>();

        ColorSet c = s.colors();
        if (c.background() != null) l.add(".backgroundColor(" + col(c.background()) + ")");
        if (c.foundation() != null) l.add(".foundationColor(" + col(c.foundation()) + ")");
        if (c.foreground() != null) l.add(".foregroundColor(" + col(c.foreground()) + ")");

        Pad p = s.padding();
        if (!p.isZero()) l.add(p.isUniform()
            ? ".padding(" + p.top() + ")"
            : ".padding(" + p.top() + ", " + p.right() + ", " + p.bottom() + ", " + p.left() + ")");
        Pad m = s.margin();
        if (!m.isZero()) l.add(m.isUniform()
            ? ".margin(" + m.top() + ")"
            : ".margin(" + m.top() + ", " + m.right() + ", " + m.bottom() + ", " + m.left() + ")");

        borderRules(s.border(), l);

        Typo t = s.typo();
        if (t.isSet()) {
            StringBuilder f = new StringBuilder(".componentFont(f -> f");
            if (!t.family().trim().isEmpty()) f.append(".family(\"").append(t.family()).append("\")");
            if (t.size() > 0)                 f.append(".size(").append(t.size()).append(")");
            if (t.weight() != 1)              f.append(".weight(").append(num(t.weight())).append("f)");
            if (t.posture() != 0)             f.append(".posture(").append(num(t.posture())).append("f)");
            if (t.spacing() != 0)             f.append(".spacing(").append(num(t.spacing())).append("f)");
            if (t.color() != null)            f.append(".color(").append(col(t.color())).append(")");
            f.append(")");
            l.add(f.toString());
        }

        Grad g = s.gradient();
        if (g.on())
            l.add(".gradient(\"g\", grad -> grad"
                + ".type(UI.GradientType." + g.type().name() + ")"
                + ".span(UI.Span." + g.span().name() + ")"
                + ".colors(" + col(g.color1()) + ", " + col(g.color2()) + ")"
                + ".clipTo(UI.ComponentArea.BODY))");

        Shade sh = s.shadow();
        if (sh.on())
            l.add(".shadow(\"s\", sh -> sh"
                + ".color(" + col(sh.color()) + ")"
                + ".blurRadius(" + sh.blur() + ")"
                + ".spreadRadius(" + sh.spread() + ")"
                + ".offset(" + sh.offsetX() + ", " + sh.offsetY() + ")"
                + ".isInset(" + sh.inset() + "))");

        Grain n = s.noise();
        if (n.on())
            l.add(".noise(\"n\", noise -> noise"
                + ".function(UI.NoiseType." + n.function().name() + ")"
                + ".colors(" + col(n.color1()) + ", " + col(n.color2()) + ")"
                + ".scale(" + num(n.scale()) + ")"
                + ".clipTo(UI.ComponentArea.BODY))");

        return l;
    }

    private static void borderRules(BorderConf b, List<String> l) {
        // Corners — concise borderRadius(..) when uniform, else per-corner.
        if (b.anyArc()) {
            if (b.cornersUniform()) {
                int w = b.arcWidthAt(UI.Corner.TOP_LEFT), h = b.arcHeightAt(UI.Corner.TOP_LEFT);
                l.add(w == h ? ".borderRadius(" + w + ")" : ".borderRadius(" + w + ", " + h + ")");
            } else {
                for (UI.Corner corner : CORNERS)
                    l.add(".borderRadiusAt(UI.Corner." + corner.name() + ", "
                        + b.arcWidthAt(corner) + ", " + b.arcHeightAt(corner) + ")");
            }
        }
        // Widths + colours — concise border(w, color) when fully uniform, else explicit.
        if (b.anyWidth()) {
            if (b.widthsUniform() && b.colorsUniform()) {
                l.add(".border(" + b.widthAt(UI.Edge.TOP) + ", " + cz(b.colorAt(UI.Edge.TOP)) + ")");
            } else {
                l.add(".borderWidths(" + b.widthAt(UI.Edge.TOP) + ", " + b.widthAt(UI.Edge.RIGHT)
                    + ", " + b.widthAt(UI.Edge.BOTTOM) + ", " + b.widthAt(UI.Edge.LEFT) + ")");
                l.add(".borderColors(" + cz(b.colorAt(UI.Edge.TOP)) + ", " + cz(b.colorAt(UI.Edge.RIGHT))
                    + ", " + cz(b.colorAt(UI.Edge.BOTTOM)) + ", " + cz(b.colorAt(UI.Edge.LEFT)) + ")");
            }
        }
    }

    private static String col(Color c) {
        return "new Color(" + c.getRed() + ", " + c.getGreen() + ", " + c.getBlue() + ", " + c.getAlpha() + ")";
    }

    /** Colour literal with a grey fallback for an unset border-edge colour. */
    private static String cz(Color c) { return col(c != null ? c : Color.GRAY); }

    /** Trim trailing ".0" so 2.0 → "2" but 0.12 stays. */
    private static String num(double d) {
        if (d == Math.rint(d)) return Integer.toString((int) d);
        return Double.toString(d);
    }

    private LookCode() {}
}