package examples.laf.app;

import examples.laf.LinenPalette;
import examples.laf.LinenSurface;
import examples.laf.LinenVariant;
import sprouts.From;
import sprouts.Tuple;
import sprouts.Val;
import sprouts.Var;
import sprouts.Viewable;
import swingtree.UI;
import swingtree.UIForAnySwing;
import swingtree.UIForPanel;
import swingtree.api.model.TableData;
import swingtree.dialogs.ConfirmAnswer;
import swingtree.layout.FlowCell;

import swingtree.CellConf;

import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JEditorPane;
import javax.swing.JLabel;
import javax.swing.JMenuBar;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextPane;
import javax.swing.KeyStroke;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import java.awt.Window;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.util.Locale;
import java.util.concurrent.TimeUnit;

import static swingtree.UI.*;

/**
 *  <h1>Flaxen — the order book of a small weaving atelier</h1>
 *
 *  A working desktop application, built with SwingTree and painted by the
 *  {@link examples.laf.LinenLookAndFeel}. It exists to answer a question a
 *  component gallery cannot: <em>what does this look-and-feel feel like when
 *  somebody is actually using it all day?</em> So there is a real order book to
 *  edit, real looms that make progress, a store room that runs down as cloth
 *  ships, and a day book that records what happened.
 *
 *  <h2>What it does</h2>
 *  <ul>
 *    <li>An <b>order book</b> of commissions in a {@code JTable} bound to an
 *        immutable {@link TableData} value. Cells are editable in place, and the
 *        view model decides what an edit is allowed to mean.</li>
 *    <li>An <b>editor</b> for the selected commission across three tabs — the
 *        commission itself, the cloth (with a woven swatch generated from the
 *        weave), and the printable delivery note.</li>
 *    <li>A <b>materials tree</b> and a <b>store room</b>, either of which
 *        filters the book; shelves run down when a commission ships and are
 *        restocked through the mill portal. The tree is a {@code UI.tree(..)}
 *        bound to a {@link MaterialNode} derived from those very shelves, so it
 *        relabels itself as they empty.</li>
 *    <li>A <b>loom floor</b> that really runs: switch it on and the looms make
 *        progress, advance their commissions from station to station, and stop
 *        when the work is done.</li>
 *    <li>A <b>day book</b> drawer recording every one of those events.</li>
 *  </ul>
 *
 *  <h2>Four SwingTree ideas it is built out of</h2>
 *  <ol>
 *    <li><b>One immutable root, reached through lenses.</b> There is no Swing
 *        state in this class and no {@code setText} anywhere in it. Every widget
 *        binds a lens into the single {@link AtelierViewModel}, and two of those
 *        lenses point at things the model <em>computes</em> rather than stores:
 *        the order book as a table value, and the one selected commission. See
 *        {@link AtelierViewModel#orderTable()} and
 *        {@link AtelierViewModel#selected()}. A third points at the store room
 *        <em>as a tree</em>, and its selection is a lens which reads a filter
 *        string as a node and writes a node back as a filter string.</li>
 *    <li><b>A table is a value, and so is a tree.</b>
 *        {@code UI.table(Var<TableData>)} is the entire binding for the order
 *        book — no {@code TableModel}, no listener, no refresh call. The
 *        materials tree is the same idea one dimension further up:
 *        {@code UI.tree(..)} over one immutable {@link MaterialNode}, with a rule
 *        per node type saying where its children live. See
 *        {@link #materialsTree()}.</li>
 *    <li><b>Pictures are values too.</b> The cloth swatch is SVG <i>text</i>
 *        generated by {@link AtelierArt} and handed to a component with
 *        {@code withStyle(svg, (text, it) -> it.image(img -> img.svg(text)))},
 *        so it is re-derived and re-rendered crisply whenever the weave
 *        changes.</li>
 *    <li><b>Convergence without state.</b> The page is a twelve-column
 *        {@code AUTO_SPAN} grid and the store room is a nested grid inside its
 *        card, so dragging the window from ultrawide to a tall strip rearranges
 *        everything and loses nothing — with no breakpoint field and no resize
 *        listener driving it.</li>
 *  </ol>
 *
 *  <h2>Working with a SwingTree-backed look-and-feel</h2>
 *  Linen paints through the same style engine the application does, and its
 *  layer of the cascade is resolved <em>after</em> the application's
 *  {@link AtelierSheet}. So this view asks the look-and-feel for the surfaces
 *  and the button roles it wants — {@code .group(LinenSurface.CARD)},
 *  {@code .group(LinenVariant.PRIMARY)} — rather than painting them itself, and
 *  the sheet is left to do what the LAF does not: typography. The two files say
 *  more about why.
 *
 *  @see examples.laf.LinenLookAndFeel
 *  @see AtelierViewModel
 */
public final class AtelierView extends JPanel
{
    // ════════════════════════════════════════════════════════════════════════
    //  The responsive design, written out as a table
    // ════════════════════════════════════════════════════════════════════════

    /*
     *  Size categories are exact fifths of a grid's reference width, so the
     *  three cards converge through four arrangements with no state at all:
     *
     *      OVERSIZE      3 |  5 |  4   materials · book · editor, side by side
     *      VERY_LARGE    3 |  5 |  4   the same three columns
     *      LARGE         4 |  8 | 12   the editor drops below, full width
     *      MEDIUM and   12 | 12 | 12   one scrolling column: a tall strip
     *      narrower
     */
    private static final int PAGE_REFERENCE_WIDTH      = 1240;
    private static final int MATERIALS_REFERENCE_WIDTH = 660;

    private static final FlowCell FULL_ROW = AUTO_SPAN( it -> it.fill(true)
            .verySmall(12).small(12).medium(12).large(12).veryLarge(12).oversize(12) );
    private static final FlowCell MATERIALS_SPAN = AUTO_SPAN( it -> it.fill(true)
            .verySmall(12).small(12).medium(12).large(4).veryLarge(3).oversize(3) );
    private static final FlowCell BOOK_SPAN = AUTO_SPAN( it -> it.fill(true)
            .verySmall(12).small(12).medium(12).large(8).veryLarge(5).oversize(5) );
    private static final FlowCell EDITOR_SPAN = AUTO_SPAN( it -> it.fill(true)
            .verySmall(12).small(12).medium(12).large(12).veryLarge(4).oversize(4) );
    /*
     *  The store-room chips. Their reference width is that of the *card*, not of
     *  the page, which is the whole trick: the same span table reads "two per
     *  row" while the card is a narrow sidebar and "three per row" once the card
     *  has become a full-width banner. Same widgets, no state.
     */
    private static final FlowCell CHIP_SPAN = AUTO_SPAN( it -> it.fill(true)
            .verySmall(12).small(6).medium(6).large(6).veryLarge(4).oversize(4) );

    /** How often the loom floor advances while it is running. */
    private static final double LOOM_PULSE_MILLIS = 150;

    /**
     *  How much of the order-book card the table gets, the loom floor taking the
     *  rest. Bound to the divider in both directions, so dragging it writes back
     *  here and the share — rather than a pixel offset — is what survives a
     *  window resize. It lives in the view rather than in the view model because
     *  it is a preference about this one card, not something the workshop knows.
     */
    private final Var<Double> bookSplit = Var.of(0.50);

    private final Var<AtelierViewModel> vm;
    private final AtelierSheet          sheet;

    // ── Lenses into the one immutable root ────────────────────────────────
    // Kept as fields rather than locals: a lens is observed only weakly by its
    // parent, so anything consumed by a raw subscription — or simply reused
    // across several builder methods — has to be held here to survive.
    private final Var<Tuple<Loom>> looms;
    private final Var<String>      search;
    private final Var<String>      materialFilter;
    private final Var<String>      selectedRef;
    private final Var<String>      journal;
    private final Var<String>      status;
    private final Var<String>      millAccount;
    private final Var<String>      millSecret;
    private final Var<Boolean>     rushOnly;
    private final Var<Boolean>     journalOpen;
    private final Var<Boolean>     loomsRunning;
    private final Var<Integer>     editorTab;

    /** The order book as an editable table value — a lens onto a projection. */
    private final Var<TableData> book;

    /** The one commission the editor writes to, and the fields inside it. */
    private final Var<Order>   order;
    private final Var<String>  client;
    private final Var<String>  due;
    private final Var<String>  notes;
    private final Var<Fibre>   fibre;
    private final Var<Weave>   weave;
    private final Var<Finish>  finish;
    private final Var<Stage>   stage;
    private final Var<Integer> metres;
    private final Var<Integer> sett;
    private final Var<Integer> widthCm;
    private final Var<Boolean> rush;

    /** The materials tree, and the position in it the order book is filtered by. */
    private final Val<MaterialNode> materials;
    private final Var<Tuple<String>> selectedMaterial;

    // ── Derived, read-only views ──────────────────────────────────────────
    private final Val<Tuple<Yarn>> store;
    private final Val<String>      headline;
    private final Val<String>      orderTitle;
    private final Val<String>      clothLine;
    private final Val<String>      emptyText;
    private final Val<String>      swatchSvg;
    private final Val<String>      journalButtonText;
    private final Val<String>      loomsButtonText;
    private final Val<String>      millButtonText;
    private final Val<String>      bookCount;
    private final Val<Boolean>     hasSelection;
    private final Val<Boolean>     bookIsEmpty;
    private final Val<Boolean>     isFiltered;
    private final Val<Boolean>     millConnected;
    private final Val<Double>      workload;
    private final Val<Integer>     bookHeight;

    /*
     *  The one raw Swing handle this view keeps. A JTable's row selection is the
     *  piece of state SwingTree wraps no binding for, so it is synchronised by
     *  hand in one place — see captureBook(..). Everything else on screen is
     *  bound, the materials tree included.
     */
    private JTable      bookTable;
    private JEditorPane docketPane;
    private JTextPane   journalPane;
    private boolean     syncingSelection;

    public AtelierView( Var<AtelierViewModel> vm, AtelierSheet sheet ) {
        this.vm    = vm;
        this.sheet = sheet;

        looms          = vm.zoomTo(AtelierViewModel::looms,          AtelierViewModel::withLooms);
        search         = vm.zoomTo(AtelierViewModel::search,         AtelierViewModel::withSearch);
        materialFilter = vm.zoomTo(AtelierViewModel::materialFilter, AtelierViewModel::withMaterialFilter);
        selectedRef    = vm.zoomTo(AtelierViewModel::selectedRef,    AtelierViewModel::withSelectedRef);
        journal        = vm.zoomTo(AtelierViewModel::journal,        AtelierViewModel::withJournal);
        status         = vm.zoomTo(AtelierViewModel::status,         AtelierViewModel::withStatus);
        millAccount    = vm.zoomTo(AtelierViewModel::millAccount,    AtelierViewModel::withMillAccount);
        millSecret     = vm.zoomTo(AtelierViewModel::millSecret,     AtelierViewModel::withMillSecret);
        rushOnly       = vm.zoomTo(AtelierViewModel::rushOnly,       AtelierViewModel::withRushOnly);
        journalOpen    = vm.zoomTo(AtelierViewModel::journalOpen,    AtelierViewModel::withJournalOpen);
        loomsRunning   = vm.zoomTo(AtelierViewModel::loomsRunning,   AtelierViewModel::withLoomsRunning);
        editorTab      = vm.zoomTo(AtelierViewModel::editorTab,      AtelierViewModel::withEditorTab);

        // The two lenses onto computed projections. Neither is a stored field of
        // the model, so both re-derive whenever any of their several inputs
        // change — and both fold what the user did back into the book.
        book  = vm.zoomTo(AtelierViewModel::orderTable, AtelierViewModel::withOrderTable);
        order = vm.zoomTo(AtelierViewModel::selected,   AtelierViewModel::withSelected);

        client  = order.zoomTo(Order::client,  Order::withClient);
        due     = order.zoomTo(Order::due,     Order::withDue);
        notes   = order.zoomTo(Order::notes,   Order::withNotes);
        fibre   = order.zoomTo(Order::fibre,   Order::withFibre);
        weave   = order.zoomTo(Order::weave,   Order::withWeave);
        finish  = order.zoomTo(Order::finish,  Order::withFinish);
        stage   = order.zoomTo(Order::stage,   Order::withStage);
        metres  = order.zoomTo(Order::metres,  Order::withMetres);
        sett    = order.zoomTo(Order::sett,    Order::withSett);
        widthCm = order.zoomTo(Order::widthCm, Order::withWidthCm);
        rush    = order.zoomTo(Order::rush,    Order::withRush);

        // The materials tree, both ways. The shape is derived from the shelves, so a
        // shipment that draws a fibre down is a new tree value; and the selection is a
        // lens which reads the filter string as a path of ids and writes a path back as
        // a filter string, so the tree, the menu's radio items and the store-room chips
        // all drive the one field without knowing about each other.
        materials        = vm.viewAs(MaterialNode.class, m -> MaterialNode.of(m.store()));
        selectedMaterial = vm.zoomTo(
                                m -> MaterialNode.pathFor(m.materialFilter()),
                                (m, path) -> m.withMaterialFilter(MaterialNode.filterFor(path)));

        store         = vm.viewAs(Tuple.classTyped(Yarn.class), AtelierViewModel::store);
        headline      = vm.viewAsString(AtelierViewModel::headline);
        emptyText     = vm.viewAsString(AtelierViewModel::emptyBookText);
        hasSelection  = vm.viewAs(Boolean.class, AtelierViewModel::hasSelection);
        isFiltered    = vm.viewAs(Boolean.class, AtelierViewModel::isFiltered);
        millConnected = vm.viewAs(Boolean.class, AtelierViewModel::millConnected);
        workload      = vm.viewAsDouble(AtelierViewModel::workload);
        bookHeight    = vm.viewAsInt(AtelierViewModel::bookHeight);
        bookCount     = book.viewAsString(table -> table.getRowCount() == 1 ? "1 commission"
                                                 : table.getRowCount() + " commissions");
        bookIsEmpty   = book.viewAs(Boolean.class, table -> table.getRowCount() == 0);

        orderTitle = order.viewAsString(Order::title);
        clothLine  = order.viewAsString(Order::cloth);
        swatchSvg  = order.viewAsString(AtelierArt::swatchSvg);

        journalButtonText = journalOpen.viewAsString(  open -> open    ? "▾  Day book" : "▸  Day book" );
        loomsButtonText   = loomsRunning.viewAsString( running -> running ? "❙❙  Looms" : "▶  Looms" );
        millButtonText    = millConnected.viewAsString(on -> on ? "Reorder yarn" : "Sign in" );

        // Model → view for the one thing Swing owns rather than we: which row of
        // the table is highlighted. Deferred to the next EDT cycle because the
        // table's own rebinding is triggered by the very same model change and
        // may not have happened yet. Both read the model when they run rather
        // than closing over the value the event carried: two of these can be
        // queued at once, and a deferred write of an outdated value is one the
        // Swing selection would report straight back as a fresh model change.
        Viewable.cast(selectedRef).onChange(From.ALL, it -> UI.runLater(this::highlightSelectedRow));
        Viewable.cast(order).onChange(From.ALL, it ->
            UI.run(() -> writeDocket(it.currentValue().orElse(Order.none()))));
        Viewable.cast(journal).onChange(From.ALL, it ->
            UI.run(() -> writeJournal(it.currentValue().orElse(""))));

        // Everything is built inside the sheet's scope, so the typography rules
        // reach every component in the tree.
        UI.use(sheet, () ->
            of(this)
            .withLayout("fill, wrap 1, ins 0, gap 0, hidemode 3")
            .withPrefSize(1300, 880)
            .withMinSize(0, 0)
            // The single place the shape of the window enters the model, and it
            // hands the numbers straight over rather than deciding what they
            // mean: a flow grid never stretches a row, so the order book has to
            // be told how tall to want to be.
            .onResize( it -> vm.update(From.VIEW, m -> m.withViewSize(it.getWidth(), it.getHeight())) )
            .add(GROW_X, menuBar())
            .add(GROW_X.and("wmin 0"), header())
            .add(GROW_X.and("wmin 0"), toolStrip())
            .add(GROW.and(PUSH).and("wmin 0"), page())
            .add(GROW_X.and("wmin 0"), dayBookDrawer())
            .add(GROW_X.and("wmin 0"), statusBar())
        );

        UI.runLater(LOOM_PULSE_MILLIS, TimeUnit.MILLISECONDS, this::pulseLoomFloor);
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Top chrome
    // ════════════════════════════════════════════════════════════════════════

    /**
     *  {@link JMenuBar} has no SwingTree factory of its own, so the bar itself is
     *  wrapped with {@code of(..)} while its contents are declared normally. The
     *  three radio items are worth a look: each one binds a boolean lens
     *  <em>into a string</em> — reading "is the filter this material?" and
     *  writing the material back — which is how a plain {@code Var<String>} ends
     *  up driving a radio group with no extra state to keep in step.
     */
    private UIForAnySwing<?, JMenuBar> menuBar() {
        Var<Boolean> allMaterials = materialFilter.zoomTo(f -> f.isEmpty(),      (f, on) -> on ? "" : f);
        Var<Boolean> plantOnly    = materialFilter.zoomTo(f -> isOrigin(f, Fibre.Origin.PLANT),
                                                          (f, on) -> on ? Fibre.Origin.PLANT.label() : "");
        Var<Boolean> animalOnly   = materialFilter.zoomTo(f -> isOrigin(f, Fibre.Origin.ANIMAL),
                                                          (f, on) -> on ? Fibre.Origin.ANIMAL.label() : "");
        ButtonGroup materials = new ButtonGroup();

        return of(new JMenuBar())
            .add(menu("File").peek( m -> m.setMnemonic(KeyEvent.VK_F) )
                .add(menuItem("New docket").peek( mi -> mi.setAccelerator(accelerator(KeyEvent.VK_N)) )
                     .onClick( it -> vm.update(AtelierViewModel::addOrder) ))
                .add(menuItem("Duplicate commission").peek( mi -> mi.setAccelerator(accelerator(KeyEvent.VK_D)) )
                     .onClick( it -> vm.update(AtelierViewModel::duplicateSelected) ))
                .add(separator())
                .add(menu("Export delivery note")
                    .add(menuItem("as PDF…").onClick( it -> exported("PDF") ))
                    .add(menuItem("as PNG…").onClick( it -> exported("PNG") ))
                    .add(menuItem("as SVG…").onClick( it -> exported("SVG") ))
                )
                .add(separator())
                .add(menuItem("Close the workshop").peek( mi -> mi.setAccelerator(accelerator(KeyEvent.VK_Q)) )
                     .onClick( it -> closeWindow() ))
            )
            .add(menu("Edit").peek( m -> m.setMnemonic(KeyEvent.VK_E) )
                .add(menuItem("Advance to the next station")
                     .onClick( it -> vm.update(AtelierViewModel::advanceSelected) ))
                .add(menuItem("Strike out of the book…").onClick( it -> confirmAndStrike() ))
                .add(separator())
                .add(menuItem("Clear all filters").onClick( it -> vm.update(AtelierViewModel::clearFilters) ))
            )
            .add(menu("View").peek( m -> m.setMnemonic(KeyEvent.VK_V) )
                .add(checkBoxMenuItem("Day book", journalOpen)
                     .peek( mi -> mi.setAccelerator(accelerator(KeyEvent.VK_J)) ))
                .add(checkBoxMenuItem("Rush jobs only", rushOnly))
                .add(checkBoxMenuItem("Run the looms", loomsRunning))
                .add(separator())
                .add(radioButtonMenuItem("All materials", allMaterials).peek(materials::add))
                .add(radioButtonMenuItem("Plant fibres",  plantOnly).peek(materials::add))
                .add(radioButtonMenuItem("Animal fibres", animalOnly).peek(materials::add))
            )
            .add(menu("Help").peek( m -> m.setMnemonic(KeyEvent.VK_H) )
                .add(menuItem("About Flaxen…").onClick( it -> UI.message(
                        "Flaxen — the order book of the Aspang weaving atelier.\n\n"
                      + "A SwingTree application, painted by the Linen look-and-feel."
                     ).titled("About Flaxen").showAsInfo() ))
            );
    }

    private UIForAnySwing<?, ?> header() {
        return
            panel().group(LinenSurface.RAIL)
            .withLayout("fill, ins 12 20 12 20, gap 14, hidemode 3", "[][grow][]")
            .withStyle( it -> it.borderAt(UI.Edge.BOTTOM, 1, LinenPalette.BORDER) )
            .add(GROW_Y,
                // Not a logo: a live picture of the cloth currently on the bench,
                // woven from the selected commission's own weave and fibre.
                box().withPrefSize(38, 38)
                .withTooltip("The cloth on the bench")
                .withStyle(swatchSvg, (svg, it) -> it
                    .image(img -> img.svg(svg).fitMode(UI.FitComponent.MIN_DIM).placement(UI.Placement.CENTER))
                )
            )
            .add(LEFT.and("wmin 0"),
                box(FILL.and(WRAP(1)).and(INS(0)).and("hidemode 3"))
                .add(GROW_X.and("wmin 0"), label("Flaxen").group(Skin.APP_TITLE))
                .add(GROW_X.and("wmin 0"), label(headline).group(Skin.APP_SUBTITLE))
            )
            .add(RIGHT,
                box(FLOW_X.and(INS(0)).and(GAP_REL(6)))
                .add(button(journalButtonText).group(LinenVariant.QUIET)
                     .withTooltip("Open the day book")
                     .onClick( it -> journalOpen.set(From.VIEW, !journalOpen.get()) ))
                .add(button(loomsButtonText).group(LinenVariant.QUIET)
                     .withTooltip("Start or stop the loom floor")
                     .onClick( it -> vm.update(AtelierViewModel::toggleLooms) ))
            );
    }

    /**
     *  The four commands that act on the selected commission.
     *  <p>
     *  A {@link javax.swing.JToolBar} lays its children out along one axis and
     *  never wraps, so its minimum width would otherwise become the window's.
     *  {@code withMinSize(0, 0)} takes that floor away: at the very narrowest the
     *  bar clips, which is what tool bars do, rather than refusing to let the
     *  window narrow at all.
     */
    private UIForAnySwing<?, ?> toolStrip() {
        return
            panel().group(LinenSurface.RAIL)
            .withLayout("fillx, ins 8 16 8 16, gap 12, hidemode 3")
            .withStyle( it -> it.borderAt(UI.Edge.BOTTOM, 1, LinenPalette.BORDER_SOFT) )
            .add(LEFT,
                toolBar().withMinSize(0, 0)
                .add(button("＋  Docket").group(LinenVariant.PRIMARY)
                     .withTooltip("Open a new commission")
                     .onClick( it -> vm.update(AtelierViewModel::addOrder) ))
                .add(button("⧉  Copy").isEnabledIf(hasSelection)
                     .withTooltip("Copy the selected commission onto a new docket")
                     .onClick( it -> vm.update(AtelierViewModel::duplicateSelected) ))
                .add(button("▸  Advance").isEnabledIf(hasSelection)
                     .withTooltip("Move the selected commission to the next station")
                     .onClick( it -> vm.update(AtelierViewModel::advanceSelected) ))
                .add(separator(Align.VERTICAL))
                .add(button("✕  Strike out").group(LinenVariant.DANGER).isEnabledIf(hasSelection)
                     .withTooltip("Take the selected commission out of the book")
                     .onClick( it -> confirmAndStrike() ))
            );
    }

    /**
     *  The filters sit on the card they filter rather than up in the tool bar.
     *  That puts them where they are used, and it is also what keeps the top of
     *  the window convergent: a {@link javax.swing.JToolBar} never wraps, so one
     *  more thing beside it would have had nowhere to go when the window narrows.
     */
    private UIForAnySwing<?, ?> filterRow() {
        return
            box(FILL).withLayout("fill, ins 0, gap 6, hidemode 3", "[][grow][][]")
            .add(fieldLabel("Filter"))
            .add(GROW_X.and("wmin 0"),
                textField(search)
                .withTooltip("Filter by docket, client, fibre, weave or station")
            )
            .add(toggleButton("Rush only", rushOnly)
                 .withTooltip("Show only the commissions somebody is waiting on"))
            .add(button("✕").group(LinenVariant.QUIET).isVisibleIf(isFiltered)
                 .withTooltip("Clear every filter")
                 .onClick( it -> vm.update(AtelierViewModel::clearFilters) ));
    }

    // ════════════════════════════════════════════════════════════════════════
    //  The page — three cards in one twelve-column grid
    // ════════════════════════════════════════════════════════════════════════

    private UIForAnySwing<?, ?> page() {
        return
            // TRANSPARENT tells Linen not to paint this scroll region — and its
            // viewport — as a sunken field. It is the page itself, so the
            // window's cream and grain must run straight through it.
            scrollPane( conf -> conf.fitWidth(true) ).group(LinenSurface.TRANSPARENT)
            .withHorizontalScrollBarPolicy(UI.Active.NEVER)
            .withScrollIncrement(26)
            .add(
                panel().group(LinenSurface.TRANSPARENT)
                .withFlowLayout(UI.HorizontalAlignment.LEFT, 16, 16)
                .withMinSize(0, 0)                     // a grid's minimum is the SUM of its children's
                .withPrefSize(PAGE_REFERENCE_WIDTH, 0) // ...and this is where the bands sit
                .withStyle( it -> it.padding(16) )
                .add(MATERIALS_SPAN, materialsCard())
                .add(BOOK_SPAN,      bookCard())
                .add(EDITOR_SPAN,    editorCard())
            );
    }

    // ── Left: the store room ──────────────────────────────────────────────

    /**
     *  A grid inside a grid — never a grid inside a MigLayout cell. A wrapping
     *  grid is asked "how tall are you at the width you are about to get?", and
     *  only another grid asks that question; a MigLayout parent would read the
     *  literal {@code 0} out of {@code withPrefSize(w, 0)} and render the whole
     *  card at zero height.
     */
    private UIForAnySwing<?, ?> materialsCard() {
        return
            panel().group(LinenSurface.CARD)
            .withFlowLayout(UI.HorizontalAlignment.LEFT, 10, 10)
            .withMinSize(0, 0)
            .withPrefSize(MATERIALS_REFERENCE_WIDTH, 0)
            .withStyle( it -> it.padding(14, 16, 16, 16) )
            .add(FULL_ROW, label("MATERIALS").group(Skin.SECTION))
            .add(FULL_ROW,
                scrollPane().withPrefSize(240, 252)
                .add(materialsTree())
            )
            .add(FULL_ROW, label("STORE ROOM").group(Skin.SECTION))
            .add(FULL_ROW, storeRail())
            .add(FULL_ROW, millPortal());
    }

    /**
     *  A bound {@code addAll(..)} <b>owns</b> the container it binds to and
     *  clears anything that was put there by hand, so a bound list always gets a
     *  panel of its own rather than sitting among siblings.
     */
    private UIForAnySwing<?, ?> storeRail() {
        return
            panel().group(LinenSurface.TRANSPARENT)
            .withFlowLayout(UI.HorizontalAlignment.LEFT, 8, 8)
            .withMinSize(0, 0)
            .withPrefSize(MATERIALS_REFERENCE_WIDTH, 0)
            .addAll(CHIP_SPAN, store, this::yarnChip);
    }

    /**
     *  One shelf of the store room. The supplier is handed the {@link Yarn}
     *  <em>value</em> rather than a lens, because a shelf is not edited in place
     *  — which is also why {@link Yarn} needs no {@code HasId}.
     *  <p>
     *  It re-enters the style-sheet scope, and has to: {@code UI.use(sheet, ..)}
     *  only binds what is built inside its lambda, while a bound {@code addAll}
     *  builds its rows again every time the tuple changes — long after the
     *  constructor returned. Without this, the first chips look right and every
     *  chip built after the first restock comes out untypeset.
     */
    private UIForAnySwing<?, ?> yarnChip( Yarn yarn ) {
        return UI.of(UI.use(sheet, () -> yarnChipBody(yarn).get(JPanel.class)));
    }

    private UIForPanel<JPanel> yarnChipBody( Yarn yarn ) {
        return
            panel().group(LinenSurface.TRANSPARENT)
            .withLayout("fill, ins 7 9 7 9, gap 7, hidemode 3", "[14!][grow][]")
            .withStyle( it -> it
                .borderRadius(9)
                .border(1, yarn.isLow() ? LinenPalette.DANGER : LinenPalette.BORDER_SOFT)
                .backgroundColor(LinenPalette.SURFACE_FIELD)
            )
            .withCursor(UI.Cursor.HAND)
            .withTooltip(yarn.isLow() ? "Running low — reorder from the mill"
                                      : "Show only commissions in " + yarn.fibre().label())
            .onMouseClick( it -> vm.update( m -> m.withMaterialFilter(
                    yarn.fibre().label().equals(m.materialFilter()) ? "" : yarn.fibre().label()) ) )
            .add(GROW_Y,
                box().withPrefSize(14, 14)
                .withStyle( it -> it.backgroundColor(yarn.fibre().shade()).borderRadius(4)
                                    .border(1, LinenPalette.BORDER) )
            )
            .add(GROW_X.and("wmin 0"), label(yarn.fibre().label()).group(Skin.META))
            .add(RIGHT, label(yarn.metresInStock() + " m").group(Skin.META));
    }

    /**
     *  Where the atelier buys its yarn. Small, but it is the one place in the
     *  application with a password in it — and a reason for one.
     */
    private UIForAnySwing<?, ?> millPortal() {
        return
            box(FILL).withLayout("fill, wrap 2, ins 6 0 0 0, gap 6, hidemode 3", "[grow][]")
            .add("span, growx", separator())
            .add("span", label("MILL PORTAL").group(Skin.SECTION))
            .add(GROW_X.and("wmin 0"), textField(millAccount).withTooltip("Your account at the yarn mill"))
            .add(label(millConnected.viewAsString( on -> on ? "✓" : "" )).group(Skin.META))
            .add(GROW_X.and("wmin 0"),
                passwordField(millSecret)
                .withTooltip("The mill's passphrase")
                .onKeyPress( it -> {
                    if ( it.getEvent().getKeyCode() == KeyEvent.VK_ENTER )
                        vm.update(AtelierViewModel::connectMill);
                })
            )
            .add(button(millButtonText).group(LinenVariant.PRIMARY)
                 .withTooltip("Sign in, then restock every shelf")
                 .onClick( it -> vm.update( m -> m.millConnected() ? m.reorderYarn() : m.connectMill() ) ));
    }

    // ── Middle: the order book and the loom floor ─────────────────────────

    private UIForAnySwing<?, ?> bookCard() {
        return
            panel().group(LinenSurface.CARD)
            .withLayout("fill, wrap 1, ins 14 16 16 16, gap 8, hidemode 3")
            .withStyle(bookHeight, (tall, it) -> it.prefSize(540, tall))
            .add(GROW_X.and("wmin 0"),
                box(FILL).withLayout("fill, ins 0, gap 8", "[grow][]")
                .add(LEFT.and("wmin 0"),
                    box(FILL.and(WRAP(1)).and(INS(0)))
                    .add(GROW_X.and("wmin 0"), label("Order book").group(Skin.CARD_TITLE))
                    .add(GROW_X.and("wmin 0"), label(bookCount).group(Skin.CARD_SUB))
                )
                .add(RIGHT, label(vm.viewAsString( m -> m.metresOnBooks() + " m" )).group(Skin.FIGURE))
            )
            .add(GROW_X.and("wmin 0"), filterRow())
            .add(GROW.and(PUSH).and("wmin 0"),
                splitPane(Align.VERTICAL).withDivisionOf(bookSplit).withDividerSize(9)
                .add(bookTable())
                .add(loomFloor())
            );
    }

    /**
     *  The whole table binding is one immutable {@link TableData} value in a
     *  mutable property: no {@code TableModel}, no listener, no refresh call. An
     *  editable value plus a mutable {@code Var} is what makes the cells
     *  editable, and every commit goes back through
     *  {@link AtelierViewModel#withOrderTable(TableData)}, which is free to
     *  refuse anything that makes no sense in a workshop.
     */
    private UIForAnySwing<?, ?> bookTable() {
        return
            box(FILL.and(WRAP(1)).and(INS(0)).and("gap 0, hidemode 3"))
            .add(GROW.and(PUSH).and("wmin 0"),
                scrollPane()
                .add(
                    table(book)
                    .peek(this::captureBook)
                    .withCellForColumn(AtelierViewModel.COL_METRES, AtelierView::rightAligned)
                )
            )
            // Gear 4: the book says why it is empty instead of just being empty.
            .add(GROW_X.and("wmin 0"),
                label(emptyText).group(Skin.EMPTY).isVisibleIf(bookIsEmpty)
                .withStyle( it -> it.padding(10, 4, 4, 4) )
            );
    }

    private UIForAnySwing<?, ?> loomFloor() {
        return
            box().withLayout("fill, wrap 1, ins 0, gap 6, hidemode 3")
            .add(GROW_X.and("gaptop 8"),
                box(FILL).withLayout("fill, ins 0, gap 8", "[grow][]")
                .add(LEFT, label("LOOM FLOOR").group(Skin.SECTION))
                .add(RIGHT, label(loomsRunning.viewAsString( on -> on ? "running" : "stopped" )).group(Skin.META))
            )
            .add(GROW.and(PUSH).and("wmin 0"),
                scrollPane().group(LinenSurface.TRANSPARENT)
                .withHorizontalScrollBarPolicy(UI.Active.NEVER)
                .add(
                    // The looms bind the *mutable* overload, which hands each row
                    // a Var<Loom> lens — and that is exactly why Loom implements
                    // HasId: it is what tells SwingTree which row is which loom.
                    box().withLayout("fillx, wrap 1, ins 0, gap 6, hidemode 3")
                    .addAll("growx, wmin 0", looms, this::loomCard)
                )
            );
    }

    private UIForAnySwing<?, ?> loomCard( Var<Loom> entry ) {
        return UI.of(UI.use(sheet, () -> loomCardBody(entry).get(JPanel.class)));
    }

    private UIForPanel<JPanel> loomCardBody( Var<Loom> entry ) {
        Var<Boolean> running = entry.zoomTo(Loom::running, Loom::withRunning);
        Val<Double>  made    = entry.viewAsDouble(Loom::fraction);
        Val<Boolean> threaded = entry.viewAs(Boolean.class, loom -> !loom.isIdle());

        return
            panel().group(LinenSurface.TRANSPARENT)
            .withLayout("fill, ins 7 10 7 10, gap 8 3, hidemode 3", "[grow][][]")
            .withStyle( it -> it.borderRadius(9).border(1, LinenPalette.BORDER_SOFT)
                                .backgroundColor(LinenPalette.SURFACE_FIELD) )
            .add("cell 0 0, growx, wmin 0",
                box(FILL).withLayout("fill, ins 0, gap 8, hidemode 3", "[][grow]")
                .add(label(entry.viewAsString(Loom::name)))
                .add(GROW_X.and("wmin 0"), label(entry.viewAsString(Loom::caption)).group(Skin.META))
            )
            .add("cell 1 0",
                toggleButton("Run", running).isEnabledIf(threaded)
                .withTooltip("Hold this loom without stopping the whole floor")
            )
            .add("cell 2 0",
                button("▸").group(LinenVariant.QUIET).isEnabledIf(threaded)
                .withTooltip("Show the commission this loom is weaving")
                .onClick( it -> vm.update( m -> m.select(entry.get().orderRef()) ) )
            )
            .add("cell 0 1 3 1, growx, wmin 0", progressBar(Align.HORIZONTAL, made));
    }

    // ── Right: the editor ─────────────────────────────────────────────────

    private UIForAnySwing<?, ?> editorCard() {
        return
            panel().group(LinenSurface.CARD)
            .withLayout("fill, wrap 1, ins 14 16 16 16, gap 8, hidemode 3")
            .withStyle(bookHeight, (tall, it) -> it.prefSize(400, tall))
            .add(GROW_X.and("wmin 0"), label(orderTitle).group(Skin.CARD_TITLE))
            .add(GROW_X.and("wmin 0"), label(clothLine).group(Skin.CARD_SUB))
            .add(GROW.and(PUSH).and("wmin 0"),
                // The tab selection is bound as one index rather than as a
                // boolean per tab: a per-tab binding has to keep several
                // properties in step with each other and can chase its own tail.
                tabbedPane(editorTab)
                .add(tab("Commission").add(commissionTab()))
                .add(tab("Cloth").add(clothTab()))
                .add(tab("Docket").add(docketTab()))
            );
    }

    private UIForAnySwing<?, ?> commissionTab() {
        return
            panel().group(LinenSurface.TRANSPARENT)
            .withLayout("fill, wrap 2, ins 14, gap 8 8, hidemode 3", "[90::120][grow]")
            .add(fieldLabel("Client"))
            .add(GROW_X.and("wmin 0"), textField(client).isEnabledIf(hasSelection))
            .add(fieldLabel("Fibre"))
            .add(GROW_X.and("wmin 0"), comboBox(fibre, Fibre::label).isEnabledIf(hasSelection))
            .add(fieldLabel("Weave"))
            .add(GROW_X.and("wmin 0"), comboBox(weave, Weave::label).isEnabledIf(hasSelection))
            .add(fieldLabel("Metres"))
            .add(GROW_X.and("wmin 0"),
                spinner(new SpinnerNumberModel(1, 1, 999, 1)).withValue(metres).isEnabledIf(hasSelection))
            .add(fieldLabel("Due"))
            .add(GROW_X.and("wmin 0"), dueField())
            .add(fieldLabel("Station"))
            .add(GROW_X.and("wmin 0"), comboBox(stage, Stage::label).isEnabledIf(hasSelection))
            .add("span, growx, gaptop 4", separator())
            .add("span, growx", checkBox("Rush job — surcharge of 20%", rush).isEnabledIf(hasSelection))
            .add("span", fieldLabel("Notes"))
            .add("span, grow, push",
                scrollPane().withPrefSize(260, 110)
                .add(
                    textArea(notes).isEnabledIf(hasSelection)
                    .peek( t -> { t.setLineWrap(true); t.setWrapStyleWord(true); } )
                )
            );
    }

    private UIForAnySwing<?, ?> clothTab() {
        return
            panel().group(LinenSurface.TRANSPARENT)
            .withLayout("fillx, wrap 2, ins 14, gap 10 8, hidemode 3", "[90::120][grow]")
            .add("span, growx",
                box(FILL).withLayout("fill, ins 0, gap 12", "[130!][grow]")
                .add(GROW_Y,
                    // Concept #3: the swatch is a value. AtelierArt turns the
                    // commission into SVG text, the style hands that text to the
                    // image layer, and a change of weave repaints a genuinely
                    // different interlacing.
                    box().withPrefSize(130, 130)
                    .withStyle(swatchSvg, (svg, it) -> it
                        .image(img -> img.svg(svg).fitMode(UI.FitComponent.MIN_DIM).placement(UI.Placement.CENTER))
                    )
                )
                .add(GROW_X.and("wmin 0"),
                    box(FILL.and(WRAP(1)).and(INS(0)).and("gap 4, hidemode 3"))
                    .add(GROW_X.and("wmin 0"), label(clothLine).group(Skin.META))
                    .add(GROW_X.and("wmin 0"),
                        label(order.viewAsString( o -> o.metres() + " m at " + o.widthCm() + " cm wide" ))
                        .group(Skin.META))
                    .add(GROW_X.and("wmin 0"), label(order.viewAsString(Order::totalAsMoney)).group(Skin.FIGURE))
                )
            )
            .add(fieldLabel("Sett"))
            .add(GROW_X.and("wmin 0"),
                box(FILL).withLayout("fill, ins 0, gap 8", "[grow][40!]")
                .add(GROW_X.and("wmin 0"), slider(Align.HORIZONTAL, 8, 40, sett).isEnabledIf(hasSelection))
                .add(label(sett.viewAsString( s -> s + "/cm" )).group(Skin.META))
            )
            .add(fieldLabel("Width"))
            .add(GROW_X.and("wmin 0"),
                box(FILL).withLayout("fill, ins 0, gap 8", "[grow][40!]")
                .add(GROW_X.and("wmin 0"), slider(Align.HORIZONTAL, 40, 180, widthCm).isEnabledIf(hasSelection))
                .add(label(widthCm.viewAsString( w -> w + " cm" )).group(Skin.META))
            )
            .add("span, growx, gaptop 4", separator())
            .add("span", fieldLabel("Edge"))
            .add("span, growx",
                box(FLOW_X.and(INS(0)).and(GAP_REL(14)))
                .add(radioButton(Finish.RAW.label(),     finishIs(Finish.RAW)).isEnabledIf(hasSelection))
                .add(radioButton(Finish.HEMMED.label(),  finishIs(Finish.HEMMED)).isEnabledIf(hasSelection))
                .add(radioButton(Finish.FRINGED.label(), finishIs(Finish.FRINGED)).isEnabledIf(hasSelection))
            );
    }

    /**
     *  The delivery note, rendered as HTML by a {@link JEditorPane}. The document
     *  is derived from the commission, so it is never stale and there is nothing
     *  to refresh.
     */
    private UIForAnySwing<?, ?> docketTab() {
        return
            panel().group(LinenSurface.TRANSPARENT)
            .withLayout("fill, wrap 1, ins 14, gap 8, hidemode 3")
            .add(GROW.and(PUSH).and("wmin 0"),
                scrollPane().withPrefSize(280, 240)
                .add(editorPane().peek(this::captureDocket))
            )
            .add(RIGHT,
                button("Print delivery note").group(LinenVariant.PRIMARY).isEnabledIf(hasSelection)
                .onClick( it -> vm.update( m -> m.note("Printed the delivery note for #" + m.selected().ref() + ".") ) )
            );
    }

    // ── Bottom: the day book and the status line ──────────────────────────

    /**
     *  A drawer rather than a fourth card: it is a log, wanted only now and
     *  then. {@code hidemode 3} on the frame's layout is what makes a hidden
     *  drawer stop reserving its row instead of leaving a gap behind.
     */
    private UIForAnySwing<?, ?> dayBookDrawer() {
        return
            panel().group(LinenSurface.RAIL).isVisibleIf(journalOpen)
            .withLayout("fill, wrap 1, ins 10 20 10 20, gap 6, hidemode 3")
            .withStyle( it -> it.borderAt(UI.Edge.TOP, 1, LinenPalette.BORDER) )
            .add(GROW_X, label("DAY BOOK").group(Skin.SECTION))
            .add(GROW_X.and("wmin 0"),
                scrollPane().withPrefSize(600, 120)
                .add(textPane().group(Skin.DOCUMENT).peek(this::captureJournal))
            );
    }

    private UIForAnySwing<?, ?> statusBar() {
        return
            panel().group(LinenSurface.RAIL)
            .withLayout("fill, ins 6 20 6 20, gap 14, hidemode 3", "[grow][120!][]")
            .withStyle( it -> it.borderAt(UI.Edge.TOP, 1, LinenPalette.BORDER_SOFT) )
            .add(GROW_X.and("wmin 0"), label(status).group(Skin.STATUS))
            .add(GROW_X, progressBar(Align.HORIZONTAL, workload)
                 .withTooltip("How far the whole book has come, weighted by metres"))
            .add(RIGHT, label(vm.viewAsString(AtelierViewModel::bookValue)).group(Skin.STATUS));
    }

    /**
     *  A right-aligned metres cell with a little air after it, so a quantity does
     *  not end up touching the date beside it. The one configurator is called in
     *  both modes: editing hands the cell straight back so the commit still
     *  converts to the column's own {@code Integer} type, and only the rendered
     *  form is decorated.
     */
    private static CellConf<JTable, Object> rightAligned( CellConf<JTable, Object> cell ) {
        if ( cell.isEditing() )
            return cell;
        boolean selected = cell.isSelected();
        String  text     = String.valueOf(cell.entry().orElse(""));
        return cell.updateView( view -> view
            .orGetUi( () -> label("") )
            .updateIf(JLabel.class, l -> {
                l.setText(text);
                l.setHorizontalAlignment(SwingConstants.RIGHT);
                l.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, UI.scale(10)));
                // Wearing the selection colour is how a renderer tells the
                // look-and-feel to fill the row; saying so here is what keeps
                // these two columns in step with the five Swing renders itself.
                l.setBackground(selected ? UIManager.getColor("Table.selectionBackground") : null);
                return l;
            })
        );
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Small shared fragments
    // ════════════════════════════════════════════════════════════════════════

    private static UIForAnySwing<?, ?> fieldLabel( String text ) {
        return label(text).group(Skin.FIELD_LABEL);
    }

    /**
     *  A lens turning the one {@link Finish} field into the boolean a radio
     *  button binds, so three radio buttons stay exclusive without a
     *  {@link ButtonGroup} and without a second copy of the state.
     */
    private Var<Boolean> finishIs( Finish wanted ) {
        return finish.zoomTo( current -> current == wanted, (current, on) -> on ? wanted : current );
    }

    /**
     *  The due date, as a {@link javax.swing.JFormattedTextField} under a mask
     *  that only accepts "12 Sep". SwingTree binds the text; the mask is Swing's
     *  own and is installed with the one {@code peek} it needs.
     */
    private UIForAnySwing<?, ?> dueField() {
        return formattedTextField()
            .peek( field -> {
                try {
                    MaskFormatter mask = new MaskFormatter("## AAA");
                    mask.setPlaceholderCharacter('_');
                    field.setFormatterFactory(new DefaultFormatterFactory(mask));
                } catch ( ParseException impossibleForALiteralMask ) {
                    throw new IllegalStateException(impossibleForALiteralMask);
                }
            })
            .withText(due)
            .isEnabledIf(hasSelection)
            .withTooltip("Day and month, as it is written on the docket");
    }

    private static KeyStroke accelerator( int key ) {
        return KeyStroke.getKeyStroke(key, InputEvent.CTRL_DOWN_MASK);
    }

    private static boolean isOrigin( String filter, Fibre.Origin origin ) {
        return origin.label().equals(filter);
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Commands that need the user, or a raw Swing component
    // ════════════════════════════════════════════════════════════════════════

    private void confirmAndStrike() {
        Order doomed = vm.get().selected();
        if ( !doomed.exists() )
            return;
        ConfirmAnswer answer = UI.confirmation(
                "Strike #" + doomed.ref() + " (" + doomed.client() + ") out of the book?\n"
              + "This cannot be undone."
            ).titled("Strike out").showAsQuestion();
        if ( answer.isYes() )
            vm.update(AtelierViewModel::deleteSelected);
    }

    private void exported( String format ) {
        vm.update( m -> m.hasSelection()
                       ? m.note("Exported the delivery note for #" + m.selected().ref() + " as " + format + ".")
                       : m.withStatus("Select a commission before exporting its delivery note.") );
    }

    private void closeWindow() {
        Window window = SwingUtilities.getWindowAncestor(this);
        if ( window != null )
            window.dispose();
    }

    /**
     *  One beat of the loom floor, re-arming itself. Scheduled once from the
     *  constructor and free while the floor is stopped:
     *  {@link AtelierViewModel#tickLooms()} then returns the very same view model
     *  and a property set to an unchanged value fires nothing at all. The loop
     *  ends with the window.
     */
    private void pulseLoomFloor() {
        vm.update(AtelierViewModel::tickLooms);
        if ( isDisplayable() )
            UI.runLater(LOOM_PULSE_MILLIS, TimeUnit.MILLISECONDS, this::pulseLoomFloor);
    }

    // ── The two hand-synchronised Swing selections ────────────────────────

    /**
     *  Captures the order book's {@link JTable} and wires its row selection to
     *  the model. SwingTree wraps no binding for a table's selection, so this is
     *  the one place in the view that adds a Swing listener by hand; the
     *  {@code syncingSelection} flag keeps the two directions from chasing each
     *  other.
     */
    private void captureBook( JTable table ) {
        this.bookTable = table;
        table.setRowHeight(UI.scale(26));
        table.setFillsViewportHeight(true);
        table.getTableHeader().setReorderingAllowed(false);
        // Shares rather than pixels: JTable hands out the card's width in
        // proportion to these, so the client name is the column that grows.
        widthOf(table, AtelierViewModel.COL_REF,     80);
        widthOf(table, AtelierViewModel.COL_CLIENT, 150);
        widthOf(table, AtelierViewModel.COL_FIBRE,   84);
        widthOf(table, AtelierViewModel.COL_METRES,  84);
        widthOf(table, AtelierViewModel.COL_DUE,     72);
        widthOf(table, AtelierViewModel.COL_STAGE,   88);
        // The book opens with a commission already chosen, and the highlight has
        // to say so; the subscription below only ever hears about *changes*.
        UI.runLater(this::highlightSelectedRow);
        table.getSelectionModel().addListSelectionListener( event -> {
            if ( event.getValueIsAdjusting() || syncingSelection )
                return;
            int row = table.getSelectedRow();
            if ( row < 0 )
                return;
            String ref = String.valueOf(table.getValueAt(row, refColumn(table)));
            vm.update(From.VIEW, m -> m.select(ref));
        });
    }

    private void highlightSelectedRow() {
        JTable table = this.bookTable;
        if ( table == null )
            return;
        String ref = selectedRef.get();
        syncingSelection = true;
        try {
            int column = refColumn(table);
            for ( int row = 0; row < table.getRowCount(); row++ )
                if ( ref.equals(String.valueOf(table.getValueAt(row, column))) ) {
                    table.setRowSelectionInterval(row, row);
                    return;
                }
            table.clearSelection();
        } finally {
            syncingSelection = false;
        }
    }

    private static void widthOf( JTable table, String columnName, int width ) {
        table.getColumnModel().getColumn(table.getColumnModel().getColumnIndex(columnName))
             .setPreferredWidth(UI.scale(width));
    }

    private static int refColumn( JTable table ) {
        return table.getColumnModel().getColumnIndex(AtelierViewModel.COL_REF);
    }

    /**
     *  Captures the delivery-note pane and the day book and feeds both by hand.
     *  <p>
     *  These two are a workaround rather than a design choice, and the only
     *  places in the view where a bound property would have been the natural
     *  answer. {@code withText(Val<String>)} sets the text with the document's
     *  listeners temporarily removed, which is how SwingTree breaks the feedback
     *  loop between a text component and its property — but a document kit that
     *  builds a <em>structured</em> view out of those very events cannot survive
     *  it. Bound that way, the {@code JEditorPane} holds the right 1.7&nbsp;kB of
     *  HTML, reports a preferred size of 23×16 and renders nothing at all, and
     *  the {@code JTextPane} runs every day-book line together on one line. Both
     *  happen under any look-and-feel, Linen or not; a plain {@code setText}, as
     *  here, works. Ordinary {@code JTextField}s and {@code JTextArea}s are
     *  unaffected and are bound normally everywhere else in this view.
     *
     *  @param pane the editor pane the docket tab was given
     */
    private void captureDocket( JEditorPane pane ) {
        this.docketPane = pane;
        pane.setContentType("text/html");
        pane.setEditable(false);
        writeDocket(vm.get().selected());
    }

    private void writeDocket( Order order ) {
        if ( docketPane != null )
            docketPane.setText(AtelierArt.docketHtml(order));
    }

    /** @see #captureDocket(JEditorPane) — the day book needs the same treatment. */
    private void captureJournal( JTextPane pane ) {
        this.journalPane = pane;
        pane.setEditable(false);
        writeJournal(vm.get().journal());
    }

    private void writeJournal( String lines ) {
        if ( journalPane != null )
            journalPane.setText(lines);
    }

    /**
     *  The store room as a tree, and the clearest single illustration in this app of
     *  what {@code UI.tree(..)} is for.
     *  <p>
     *  There is no {@code TreeModel} here, no {@code DefaultMutableTreeNode} graph to
     *  build and no selection listener to wire. There is one value —
     *  {@link MaterialNode}, derived from the shelves — and a rule per node type
     *  saying where that type keeps its children and how it is labelled. Selecting a
     *  node writes the filter; filtering elsewhere moves the selection.
     *  <p>
     *  Two things are worth watching while the app runs. Shipping a commission draws
     *  its fibre down, which rewrites the whole tree value, and yet the branches the
     *  user has open stay open — a bound tree identifies its nodes by
     *  {@link MaterialNode#id()}, not by their contents, so an edit cannot invalidate
     *  a path. And the bolt whose stock crosses the low-water mark relabels itself on
     *  the spot, because its label is a function of the value rather than a string
     *  somebody remembered to update.
     */
    private UIForAnySwing<?, ?> materialsTree() {
        return
            tree(MaterialNode.class, materials, conf -> conf
                .nodesOf(MaterialNode.StoreRoom.class, it -> it
                    .children(MaterialNode.StoreRoom::shelves)
                    .text(MaterialNode.StoreRoom::label)
                    .toolTip( room -> "Everything the atelier has to weave with" )
                )
                .nodesOf(MaterialNode.Shelf.class, it -> it
                    .children(MaterialNode.Shelf::bolts)
                    .text( shelf -> shelf.label() + "  ·  " + shelf.bolts().size() )
                    .toolTip( shelf -> "Show only " + shelf.label().toLowerCase(Locale.ROOT) + " fibres" )
                )
                .nodesOf(MaterialNode.Bolt.class, it -> it
                    .text( bolt -> bolt.isLow() ? bolt.label() + "  ·  running low" : bolt.label() )
                    .toolTip( bolt -> bolt.metresInStock() + " m on the shelf" )
                )
            )
            .withSelection(selectedMaterial)
            .withInitialExpansionDepth(2);
    }
}
