name: Build And Test on All OSs
on: [push, pull_request]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [1.8, 11, 17]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup xvfb for screen 0
        run: Xvfb :1 -screen 0 1600x1200x24 &
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: check
        env:
          DISPLAY: :1
      - name: Tear down xvfb on Linux and macOS
        run: killall Xvfb
        if: runner.os != 'Windows'
      - name: Tear down xvfb on Windows
        run: taskkill /F /IM Xvfb*
        if: runner.os == 'Windows'